### ISSUE TITLE
Author + Editor w pod-nagłówku strony

### ISSUE THREAD

**Issue by alucard87pl** [KocproZ/MDPages#12]
Krótko mówiąc, fajnie by było w tym miejscu:
![](https://imgs.alucard87pl.me/2018-03-18_18-31-42-Cxp2s1.png)
oprócz `Author:` było także `Editor(s):`

Bzdura, ale chyba przydatne.

**Comment by Kuboczoch** [comment]
Old issue, closed by rewrited frontend
