### ISSUE TITLE
Nie działa upload plików

### ISSUE THREAD

**Issue by Kuboczoch** [KocproZ/MDPages#2]
https://img.bymarcin.com/2018-02-06_15-46-01_kcUh49dkbwe70K2F.png

**Comment by KocproZ** [comment]
Dzieje się tak przy plikach większych niż 10MB

**Comment by Kuboczoch** [comment]
mały plik configu

**Comment by KocproZ** [comment]
Można uploadować tylko pliki z [tymi](https://github.com/KocproZ/MDPages/blob/c305e6971322f0bada582a4543f0d5df7aa59479/src/main/java/ovh/kocproz/markpages/service/FileService.java#L30) mime-typami

**Comment by marcin212** [comment]
Czemu tam nie ma txt? Ja próbowałem wgrać zdjęcie: https://img.bymarcin.com/2018-02-07_10-32-03_yQLV665vBnpXwxqD.png

**Comment by KocproZ** [comment]
Nie chcieliśmy, aby można było tam wgrywać wszystko (markdown pozwala tylko na embeddowanie obrazów). Możliwe, że usuniemy sprawdzanie mime-typów, bo i tak jest już limit wielkości pliku ustawiany przez użytkownika. Hubert już zaktualizował wiki, więc zdjęcie powinno teraz się wgrać.

**Comment by marcin212** [comment]
Ok, ale gdzie jest przycisk dodaj plik? 
https://img.bymarcin.com/2018-02-07_10-49-29_waGrMFs8cyVpIWWU.png
https://img.bymarcin.com/2018-02-07_10-50-13_EIIOhGjDMrczyMKU.png

**Comment by KocproZ** [comment]
Po zmianie gui @Kuboczoch zapomniał go dodać (Co pewnie zrobi jeszcze dzisiaj).
Możesz tam się dostać ręcznie: /files/upload

**Comment by Kuboczoch** [comment]
Zrobione, został dodany przycisk w /files
