### ISSUE TITLE
Better list of files

### ISSUE THREAD

**Issue by KocproZ** [KocproZ/MDPages#5]
Fajnie, gdyby klikając w kod pliku jego link kopiował się do schowka.

**Comment by KocproZ** [comment]
Może być taka ładna tabelka jak w /list.

**Comment by Kuboczoch** [comment]
Nie chce przerabiać czyjegoś kodu.
@KocproZ możesz zrobić tak samo jak Hubertus czyli na tabeli

**Comment by KocproZ** [comment]
Jest na tabeli i jest ładne
